### ISSUE TITLE
Package the project grid shift with the project

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/qgis-mergin-plugin#184]
It will be a good to have an option during upload, for the plugin to see if the project is using a grid shift. If so, prompt the user (maybe with some text saying: if not sure, press YES), if they want to use the grid shift in their project.

It then copies the grid shift for the current project from QGIS proj folder to the project folder and uploads. See: https://help.inputapp.io/howto/proj

**Comment by saberraz** [comment]
See https://github.com/lutraconsulting/qgis-mergin-plugin/issues/197

**Comment by alexbruy** [comment]
Fixed in #455
