### ISSUE TITLE
Python error when canceling the synchronization

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/qgis-mergin-plugin#292]
Plugin version: 2021.4.2
There are two crashes during cancellation of synchronization of the changes.
1) json.decoder.JSONDecodeError
2) Mergin.mergin.common.ClientError

Also QGIS is very slow after the crash. Mouse cursor show it is still working on something

https://user-images.githubusercontent.com/83582181/133760768-b25c847a-ee7d-4d45-bae5-c2671bee4abd.mp4

An error has occurred while executing Python code: 

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
Traceback (most recent call last):
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python/plugins/Mergin/sync_dialog.py", line 57, in cancel_operation
    self.push_cancel()
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python/plugins/Mergin/sync_dialog.py", line 238, in push_cancel
    push_project_cancel(self.job)
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python/plugins/Mergin/mergin/client_push.py", line 296, in push_project_cancel
    job.server_resp = json.load(resp_cancel)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Python version: 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0] 
QGIS version: 3.20.2-Odense Odense, 9f59a15664 

Python Path:
/usr/share/python-wheels/webencodings-0.5.1-py2.py3-none-any.whl
/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl
/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl
/usr/share/python-wheels/progress-1.5-py2.py3-none-any.whl
/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl
/usr/share/python-wheels/chardet-3.0.4-py2.py3-none-any.whl
/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl
/usr/share/python-wheels/toml-0.10.0-py2.py3-none-any.whl
/usr/share/python-wheels/lockfile-0.12.2-py2.py3-none-any.whl
/usr/share/python-wheels/idna-2.8-py2.py3-none-any.whl
/usr/share/python-wheels/distlib-0.3.0-py2.py3-none-any.whl
/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl
/usr/share/python-wheels/ipaddr-2.2.0-py2.py3-none-any.whl
/usr/share/python-wheels/wheel-0.34.2-py2.py3-none-any.whl
/usr/share/python-wheels/msgpack-0.6.2-py2.py3-none-any.whl
/usr/share/python-wheels/html5lib-1.0.1-py2.py3-none-any.whl
/usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl
/usr/share/python-wheels/appdirs-1.4.3-py2.py3-none-any.whl
/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl
/usr/share/python-wheels/colorama-0.4.3-py2.py3-none-any.whl
/usr/share/python-wheels/certifi-2019.11.28-py2.py3-none-any.whl
/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl
/usr/share/python-wheels/setuptools-44.0.0-py2.py3-none-any.whl
/usr/share/python-wheels/pip-20.0.2-py2.py3-none-any.whl
/usr/share/python-wheels/six-1.14.0-py2.py3-none-any.whl
/usr/share/python-wheels/pyparsing-2.4.6-py2.py3-none-any.whl
/usr/share/python-wheels/packaging-20.3-py2.py3-none-any.whl
/usr/share/qgis/python
/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python
/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/jozef/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python
.
/home/jozef/Lutra/projects/17.9/basic_project

-----------------
An error has occurred while executing Python code: 

Mergin.mergin.common.ClientError: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. 
Traceback (most recent call last):
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python/plugins/Mergin/mergin/client.py", line 186, in _do_request
    return self.opener.open(request)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: NOT FOUND

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python/plugins/Mergin/sync_dialog.py", line 57, in cancel_operation
    self.push_cancel()
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python/plugins/Mergin/sync_dialog.py", line 238, in push_cancel
    push_project_cancel(self.job)
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python/plugins/Mergin/mergin/client_push.py", line 299, in push_project_cancel
    raise err
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python/plugins/Mergin/mergin/client_push.py", line 295, in push_project_cancel
    resp_cancel = job.mc.post("/v1/project/push/cancel/%s" % job.transaction_id)
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python/plugins/Mergin/mergin/client.py", line 208, in post
    return self._do_request(request)
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python/plugins/Mergin/mergin/client.py", line 176, in wrapper
    return f(self, *args)
  File "/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python/plugins/Mergin/mergin/client.py", line 190, in _do_request
    raise ClientError(info.get("detail"))
Mergin.mergin.common.ClientError: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Python version: 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0] 
QGIS version: 3.20.2-Odense Odense, 9f59a15664 

Python Path:
/usr/share/python-wheels/webencodings-0.5.1-py2.py3-none-any.whl
/usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl
/usr/share/python-wheels/contextlib2-0.6.0-py2.py3-none-any.whl
/usr/share/python-wheels/progress-1.5-py2.py3-none-any.whl
/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl
/usr/share/python-wheels/chardet-3.0.4-py2.py3-none-any.whl
/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl
/usr/share/python-wheels/toml-0.10.0-py2.py3-none-any.whl
/usr/share/python-wheels/lockfile-0.12.2-py2.py3-none-any.whl
/usr/share/python-wheels/idna-2.8-py2.py3-none-any.whl
/usr/share/python-wheels/distlib-0.3.0-py2.py3-none-any.whl
/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl
/usr/share/python-wheels/ipaddr-2.2.0-py2.py3-none-any.whl
/usr/share/python-wheels/wheel-0.34.2-py2.py3-none-any.whl
/usr/share/python-wheels/msgpack-0.6.2-py2.py3-none-any.whl
/usr/share/python-wheels/html5lib-1.0.1-py2.py3-none-any.whl
/usr/share/python-wheels/pep517-0.8.2-py2.py3-none-any.whl
/usr/share/python-wheels/appdirs-1.4.3-py2.py3-none-any.whl
/usr/share/python-wheels/distro-1.4.0-py2.py3-none-any.whl
/usr/share/python-wheels/colorama-0.4.3-py2.py3-none-any.whl
/usr/share/python-wheels/certifi-2019.11.28-py2.py3-none-any.whl
/usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl
/usr/share/python-wheels/setuptools-44.0.0-py2.py3-none-any.whl
/usr/share/python-wheels/pip-20.0.2-py2.py3-none-any.whl
/usr/share/python-wheels/six-1.14.0-py2.py3-none-any.whl
/usr/share/python-wheels/pyparsing-2.4.6-py2.py3-none-any.whl
/usr/share/python-wheels/packaging-20.3-py2.py3-none-any.whl
/usr/share/qgis/python
/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python
/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/jozef/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/jozef/.local/share/QGIS/QGIS3/profiles/test/python
.
/home/jozef/Lutra/projects/17.9/basic_project

**Comment by alexbruy** [comment]
Seems fixed in the latest plugin/client builds, I can't trigger Python error anymore and busy cursor is reset back to arrow after cancellation.

**Comment by jozef-budac** [comment]
Yes, I can't simulate this also. We can close this
