### ISSUE TITLE
Plugin doesn't close project internally,  when it is removed locally

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/qgis-mergin-plugin#293]
Version 2021.4.2

When I have opened and synchronized project, the plugin didn't change it's state to closed internally. So for example, icon for synchronization is still active and I can press it. It is expected that plugin shows and error in this case.

https://user-images.githubusercontent.com/83582181/133763821-b057dc3d-2ea5-4806-b806-99c2c5fd10ab.mp4

**Comment by alexbruy** [comment]
This seems fixed in the latest versions of plugin.
