### ISSUE TITLE
Problem updating the plugin, when a Mergin project is open

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/qgis-mergin-plugin#374]
'Plugin installation failed: Failed to unzip the plugin package. Probably it's broken or missing from the repository. You may also want to make sure that you have write permission to the plugin directory'
This seems to only occur when the person has a mergin project open and if the close the project they can then update successfully.

**Comment by wonder-sk** [comment]
This is another instance of #504 - closing this in favor of that one
