### ISSUE TITLE
Packaging a new project only works ~25% of the time

### ISSUE THREAD

**Issue by AesculusK** [MerginMaps/qgis-mergin-plugin#410]
Hello,

I find I have to package most projects from QGIS at least three or four times before it works. Sometimes it appears to have worked, and other times I get a non-specific error message. Either way, the project won't load in Input and I find that although the project shows up on Mergin, there are no files. I'm not doing something wrong, because if I just try it a few times, eventually it goes through.

Thanks!

Katherine

**Comment by alexbruy** [comment]
Can you share the project which does not work or maybe provide exact text of the error message?

**Comment by AesculusK** [comment]
Hi Alexander,

Thanks for following up! Can you please share your username so I can invite
you as a collaborator?

Sometimes there is no error. Next time there is one, I will send it over.

Best,

Katherine Naegele
She/Her
Consulting Arborist
Master of Forestry, UC Berkeley
International Society of Arboriculture Certified Arborist #WE-9658A
ISA Tree Risk Assessment Qualification Credentialed
American Society of Consulting Arborists, Member
***@***.***
(408) 201-9607 (direct cell)
(408) 675-1729 (main cell)
aacarbor.com
Yelp
<https://www.yelp.com/biz/aesculus-arboricultural-consulting-mountain-view>

<http://aacarbor.com>

**Comment by alexbruy** [comment]
You can share project with the `support` account.

**Comment by PeterPetrik** [comment]
no response for 28 days, closing. Please reopen if the issue persists
