### ISSUE TITLE
Raster layers do not get packaged correctly

### ISSUE THREAD

**Issue by AesculusK** [MerginMaps/qgis-mergin-plugin#411]
Hello,

Starting today, when I package a new project, the raster layers point to the old raster files in my original local folder, NOT to the raster files packaged with the project. If I then add the raster files packaged with the project, they work just fine.

This is a strange and frustrating issue to suddenly be encountering after months of using Mergin.

Thanks,

Katherine

**Comment by alexbruy** [comment]
Should be fixed by #445. Please reopen if necessary.
