### ISSUE TITLE
Couldn't load plugin 'Mergin' due to an error when calling its classFactory() method - QGIS 3.16

### ISSUE THREAD

**Issue by pwflint** [MerginMaps/qgis-mergin-plugin#429]
I've run into the same issue as this [previous issue](https://github.com/MerginMaps/qgis-mergin-plugin/issues/230#issue-874261468) except I am running the current LTR specified in the comments. Reinstalling via Plug-in manager has not resolved. Of interest, it is currently marked as installed in the plug-in manager but not an active plug-in in the about/license window.

![Screen Shot 2022-06-15 at 9 46 20 AM](https://user-images.githubusercontent.com/73616669/173842977-526dd09e-9b46-4913-8d8e-f3a6ffde8523.png)

Thought welcome

PWF

**Comment by alexbruy** [comment]
Already fixed in 2022.4.1
