### ISSUE TITLE
When GeoPackage is in edit mode with pending changes and selecting Show local changes

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/qgis-mergin-plugin#432]
...it would be good to ask user to either save or cancel changes. Currently, it does not show the pending changes made to the GeoPackage and not saved.

**Comment by ldebek** [comment]
Can't reproduce this issue. It seems like it was fixed in the latest version of the plugin.
![save](https://user-images.githubusercontent.com/11883222/180780836-b5bbf4a5-9022-4efb-84fe-af49963fa5a2.PNG)

**Comment by alexbruy** [comment]
Fixed with #447
