### ISSUE TITLE
Reorder elements in the settings/config dialog

### ISSUE THREAD

**Issue by roya0045** [MerginMaps/qgis-mergin-plugin#441]
Greetings,

This is a minor suggestion for improvement. When using the config dialog to provide credentials, the tabing order has change in the redesigned layout.

This means that pressing tab when the username textbox is active doesn't lead to the password textbox but through a few others elements beforehand. 

It would be nice to have tabs go in descending order instead of jumping, all around. This is simply to login more quickly.

Thanks,

**Comment by saberraz** [comment]
Hi @roya0045 is it not a duplicate of https://github.com/MerginMaps/qgis-mergin-plugin/issues/431?

**Comment by roya0045** [comment]
> Hi @roya0045 is it not a duplicate of #431?

You're right, I completely overlooked it.
