### ISSUE TITLE
Crash app

### ISSUE THREAD

**Issue by CafarellaL** [MerginMaps/qgis-mergin-plugin#472]
What is the bug or the crash?

Crash ID: [ea5189dc03e3a6336b57664445950cc54fbd5c97](https://github.com/qgis/QGIS/search?q=ea5189dc03e3a6336b57664445950cc54fbd5c97&type=Issues)

Stack Trace

QSortFilterProxyModel::parent :
QModelIndex::parent :
QTableView::visualRect :
QAbstractItemView::updateEditorGeometries :
QAbstractItemView::updateGeometries :
QTableView::updateGeometries :
QAbstractItemView::doItemsLayout :
QTableView::doItemsLayout :
QTableView::visualRect :
QAbstractItemView::keyPressEvent :
QAbstractItemView::focusNextPrevChild :
QWidget::focusNextPrevChild :
QWidget::focusNextPrevChild :
QWidgetPrivate::hide_helper :
QWidgetPrivate::setVisible :
QWidget::setVisible :
QAbstractItemView::rowsAboutToBeRemoved :
QObject::qt_static_metacall :
QAbstractItemModel::beginRemoveRows :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::beginRemoveRows :
QgsAttributeTableModel::removeRows :
QgsAttributeTableModel::featuresDeleted :
QObject::qt_static_metacall :
QgsVectorLayer::featuresDeleted :
QgsVectorLayer::onFeatureDeleted :
QObject::qt_static_metacall :
QgsVectorLayerEditBuffer::featureDeleted :
QgsVectorLayerEditBuffer::commitChanges :
QgsVectorLayer::commitChanges :
QgisApp::saveVectorLayerEdits :
QgisApp::saveEdits :
QgsAttributeTableDialog::mActionSaveEdits_triggered :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.5-Bia?owie?a
QGIS code revision: https://github.com/qgis/QGIS/commit/c27231782f46fb67183d8d26bfe41b93cb30f1b6
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

**Comment by CafarellaL** [comment]
A new error:
Python Stack Trace
Windows fatal exception: access violation

Current thread 0x000044f8 (most recent call first):



Stack Trace


QSortFilterProxyModel::parent :
QModelIndex::parent :
QTableView::visualRect :
QAbstractItemView::updateEditorGeometries :
QAbstractItemView::updateGeometries :
QTableView::updateGeometries :
QAbstractItemView::doItemsLayout :
QTableView::doItemsLayout :
QAbstractItemView::updateEditorGeometries :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QgsAttributeTableModel::featureAdded :
QObject::qt_static_metacall :
QgsVectorLayerCache::featureAdded :
QObject::qt_static_metacall :
QgsVectorLayer::featureAdded :
QObject::qt_static_metacall :
QgsVectorLayerEditBuffer::featureAdded :
QUndoStack::push :
QgsVectorLayerEditBuffer::addFeature :
QgsVectorLayer::addFeature :
QgsVectorLayerTools::copyMoveFeatures :
QgsMapToolMoveFeature::cadCanvasReleaseEvent :
QgsMapToolAdvancedDigitizing::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.28.0-Firenze
QGIS code revision: ed3ad0430f3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.2
Running against GDAL: 3.5.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

**Comment by wonder-sk** [comment]
These crashes look like they are coming from QGIS and its attribute table, unrelated to Mergin Maps plugin, please report them in QGIS issue tracker, with some details how to reproduce them...
