### ISSUE TITLE
Changing the colors in survey

### ISSUE THREAD

**Issue by tscott71** [MerginMaps/qgis-mergin-plugin#487]
I'm building an app for an internship to be used to inventory trees. I want to differentiate between the sections. The easy way seemed to be change the heading color. It does nothing.
What am I missing?

**Comment by wonder-sk** [comment]
Mergin Maps mobile app currently does not support customization of colors - it may be added in the future.

**Comment by wonder-sk** [comment]
If you'd like to have this feature supported, please add it to https://wishlist.merginmaps.com/ (where others can also vote for it easily)

I will close this ticket, as it is not directly related to the plugin, given that it is the mobile app missing this functionality.
